"""ГАЛИТ -- интегрированный flow assurance для позднестадийного фонда.

Прогноз галита, кальцита, АСПО и CO2-коррозии на единой шкале риска
с подбором технологии из арсенала НГДУ и расчётом экономического эффекта.
"""

__version__ = "0.1.0"

from .corrosion import CorrosionConditions, corrosion_rate_1995, corrosion_severity
from .integrated import (
    BASELINE_CALIBRATION,
    DataProvenance,
    DataQuality,
    DataQualityError,
    DEFAULT_RISK_POLICY,
    DiagnosisResult,
    MECHANISM_WEIGHTS,
    RiskPolicy,
    RuntimeCalibration,
    ScenarioInterval,
    UncertaintyConfig,
    UncertaintyResult,
    WellCase,
    assess_quality,
    diagnose,
    rank_wells,
)
from .forecast import (
    CorrosionIntegrityInput,
    ForecastCalibrationEvidence,
    ForecastCalibrationMetadata,
    ForecastConfig,
    ForecastEvent,
    ForecastHistory,
    ForecastMechanism,
    ForecastSnapshot,
    ForecastStatus,
    ForecastSummary,
    LikelihoodCategory,
    ObservedForecastEvent,
    TemporalEvidence,
    WellForecast,
    forecast_well,
)
from .master_plan import (
    DEFAULT_MASTER_PLAN_POLICY,
    DiagnosedWell,
    MasterPlan,
    MasterPlanPolicy,
    MasterPlanSummary,
    MasterTask,
    OilLossEstimate,
    generate_master_plan,
)
from .risk_economics import (
    FORMULAS as RISK_ECONOMICS_FORMULAS,
    RiskEconomicsBreakdown,
    RiskEconomicsInput,
    RiskEconomicsResult,
    RiskEconomicsStatus,
    calculate_risk_economics,
)
from .scenarios import (
    EffectOverride,
    ScenarioChanges,
    ScenarioComparison,
    ScenarioEconomics,
    ScenarioSnapshot,
    ScenarioStatus,
    compare_scenario,
)
from .scale import WaterAnalysis, halite_saturation_index, stiff_davis_index
from .wax import WaxProperties, wax_onset_depth
from .wellbore import (
    FluidProperties,
    ProductionRate,
    ThermalParams,
    WellGeometry,
    pressure_profile,
    temperature_profile,
)
from .treatments import (
    DEFAULT_MIN_SAMPLE_SIZE,
    SCHEMA_VERSION as TREATMENT_SCHEMA_VERSION,
    TreatmentConflictError,
    TreatmentNotFoundError,
    TreatmentRecord,
    TreatmentRepository,
    TreatmentStatus,
    TreatmentStorageError,
    compare_reagents,
    new_treatment,
    treatment_summary,
)
from .passport import (
    ALLOWED_ATTACHMENT_MIMES,
    MAX_ATTACHMENT_SIZE,
    PASSPORT_SCHEMA_VERSION,
    AttachmentMetadata,
    PassportConflictError,
    PassportEvent,
    PassportEventType,
    PassportNotFoundError,
    PassportRepository,
    PassportStorageError,
    new_passport_event,
    passport_summary,
    passport_timeline,
    safe_attachment_name,
)

__all__ = [
    "CorrosionIntegrityInput",
    "ForecastCalibrationEvidence",
    "ForecastCalibrationMetadata",
    "ForecastConfig",
    "ForecastEvent",
    "ForecastHistory",
    "ForecastMechanism",
    "ForecastSnapshot",
    "ForecastStatus",
    "ForecastSummary",
    "LikelihoodCategory",
    "ObservedForecastEvent",
    "TemporalEvidence",
    "WellForecast",
    "forecast_well",
    "BASELINE_CALIBRATION",
    "CorrosionConditions",
    "DataProvenance",
    "DataQuality",
    "DataQualityError",
    "DEFAULT_RISK_POLICY",
    "DEFAULT_MASTER_PLAN_POLICY",
    "DiagnosedWell",
    "DiagnosisResult",
    "MasterPlan",
    "MasterPlanPolicy",
    "MasterPlanSummary",
    "MasterTask",
    "OilLossEstimate",
    "RISK_ECONOMICS_FORMULAS",
    "RiskEconomicsBreakdown",
    "RiskEconomicsInput",
    "RiskEconomicsResult",
    "RiskEconomicsStatus",
    "calculate_risk_economics",
    "EffectOverride",
    "ScenarioChanges",
    "ScenarioComparison",
    "ScenarioEconomics",
    "ScenarioSnapshot",
    "ScenarioStatus",
    "compare_scenario",
    "MECHANISM_WEIGHTS",
    "RiskPolicy",
    "RuntimeCalibration",
    "ScenarioInterval",
    "UncertaintyConfig",
    "UncertaintyResult",
    "FluidProperties",
    "ProductionRate",
    "ThermalParams",
    "WaterAnalysis",
    "WaxProperties",
    "WellCase",
    "WellGeometry",
    "assess_quality",
    "corrosion_rate_1995",
    "corrosion_severity",
    "diagnose",
    "generate_master_plan",
    "halite_saturation_index",
    "pressure_profile",
    "rank_wells",
    "stiff_davis_index",
    "temperature_profile",
    "wax_onset_depth",
    "DEFAULT_MIN_SAMPLE_SIZE",
    "TREATMENT_SCHEMA_VERSION",
    "TreatmentConflictError",
    "TreatmentNotFoundError",
    "TreatmentRecord",
    "TreatmentRepository",
    "TreatmentStatus",
    "TreatmentStorageError",
    "compare_reagents",
    "new_treatment",
    "treatment_summary",
    "ALLOWED_ATTACHMENT_MIMES",
    "MAX_ATTACHMENT_SIZE",
    "PASSPORT_SCHEMA_VERSION",
    "AttachmentMetadata",
    "PassportConflictError",
    "PassportEvent",
    "PassportEventType",
    "PassportNotFoundError",
    "PassportRepository",
    "PassportStorageError",
    "new_passport_event",
    "passport_summary",
    "passport_timeline",
    "safe_attachment_name",
]
