"""ГАЛИТ -- интегрированный flow assurance для позднестадийного фонда.

Прогноз галита, кальцита, АСПО и CO2-коррозии на единой шкале риска
с подбором технологии из арсенала НГДУ и расчётом экономического эффекта.
"""

__version__ = "0.1.0"

from .compatibility import (
    MODEL_VERSION as COMPATIBILITY_MODEL_VERSION,
    CompatibilityResult,
    CompatibilityWater,
    DepositionLocation,
    DoseResponseCurve,
    DoseResponsePoint,
    InhibitorRecommendation,
    MineralScreen,
    ProfilePoint,
    RatioScreen,
    UnsafeInterval,
    default_mix_fractions,
    evaluate_compatibility,
    mix_waters,
    screen_minerals,
)
from .corrosion import CorrosionConditions, corrosion_rate_1995, corrosion_severity
from .chemicals import (
    CANONICAL_DOSE_UNIT,
    SCHEMA_VERSION as CHEMICAL_SCHEMA_VERSION,
    ChemicalConflictError,
    ChemicalNotFoundError,
    ChemicalProduct,
    ChemicalRecommendation,
    ChemicalRepository,
    ChemicalStorageError,
    DoseResponseEnvelope as ChemicalDoseResponseEnvelope,
    DoseResponsePoint as ChemicalDoseResponsePoint,
    StockLot,
    StockReservation,
    StockTransaction,
    convert_quantity,
    deterministic_consumption_forecast,
    dose_to_kg_m3,
    recommend_products,
    shortage_report,
)
from .integrated import (
    BASELINE_CALIBRATION,
    DataProvenance,
    DataQuality,
    DataQualityError,
    DEFAULT_RISK_POLICY,
    DiagnosisResult,
    MECHANISM_WEIGHTS,
    RiskPolicy,
    RuntimeCalibration,
    ScenarioInterval,
    UncertaintyConfig,
    UncertaintyResult,
    WellCase,
    assess_quality,
    diagnose,
    rank_wells,
    water_compatibility,
)
from .forecast import (
    CorrosionIntegrityInput,
    ForecastCalibrationEvidence,
    ForecastCalibrationMetadata,
    ForecastConfig,
    ForecastEvent,
    ForecastHistory,
    ForecastMechanism,
    ForecastSnapshot,
    ForecastStatus,
    ForecastSummary,
    LikelihoodCategory,
    ObservedForecastEvent,
    TemporalEvidence,
    WellForecast,
    forecast_well,
)
from .field_map import (
    FieldMapData,
    FieldMapPoint,
    FieldMapSummary,
    STATUS_COLORS as MAP_STATUS_COLORS,
    STATUS_LABELS as MAP_STATUS_LABELS,
    map_status,
    prepare_field_map,
    valid_coordinates,
)
from .master_plan import (
    DEFAULT_MASTER_PLAN_POLICY,
    DiagnosedWell,
    MasterPlan,
    MasterPlanPolicy,
    MasterPlanSummary,
    MasterTask,
    OilLossEstimate,
    generate_master_plan,
)
from .risk_economics import (
    FORMULAS as RISK_ECONOMICS_FORMULAS,
    RiskEconomicsBreakdown,
    RiskEconomicsInput,
    RiskEconomicsResult,
    RiskEconomicsStatus,
    calculate_risk_economics,
)
from .scenarios import (
    EffectOverride,
    ScenarioChanges,
    ScenarioComparison,
    ScenarioEconomics,
    ScenarioSnapshot,
    ScenarioStatus,
    compare_scenario,
)
from .scale import WaterAnalysis, halite_saturation_index, stiff_davis_index
from .wax import WaxProperties, wax_onset_depth
from .wellbore import (
    FluidProperties,
    ProductionRate,
    ThermalParams,
    WellGeometry,
    pressure_profile,
    temperature_profile,
)
from .treatments import (
    DEFAULT_MIN_SAMPLE_SIZE,
    SCHEMA_VERSION as TREATMENT_SCHEMA_VERSION,
    TreatmentConflictError,
    TreatmentNotFoundError,
    TreatmentRecord,
    TreatmentRepository,
    TreatmentStatus,
    TreatmentStorageError,
    compare_reagents,
    new_treatment,
    treatment_analytics,
    treatment_effect,
    treatment_summary,
    treatments_from_csv,
    treatments_to_csv,
)
from .equipment import (
    DISCLAIMER as EQUIPMENT_DISCLAIMER,
    EQUIPMENT_SCHEMA_VERSION,
    MODEL_VERSION as EQUIPMENT_MODEL_VERSION,
    EquipmentConflictError,
    EquipmentForecast,
    EquipmentMetadata,
    EquipmentNotFoundError,
    EquipmentRepository,
    EquipmentRiskPolicy,
    EquipmentStorageError,
    LiftType,
    RiskCause,
    TelemetrySnapshot,
    forecast_equipment,
    normalize_lift,
    telemetry_csv_template,
    telemetry_from_csv,
    telemetry_to_csv,
)
from .watercut import (
    DISCLAIMER as WATERCUT_DISCLAIMER,
    POLICY_VERSION as WATERCUT_POLICY_VERSION,
    SCHEMA_VERSION as WATERCUT_SCHEMA_VERSION,
    InjectionHistory,
    InjectorCandidate,
    OilForecastPoint,
    ProductionHistory,
    WatercutConflictError,
    WatercutDiagnosis,
    WatercutLink,
    WatercutNotFoundError,
    WatercutPolicy,
    WatercutRepository,
    WatercutStorageError,
    WellMetadata,
    bearing_deg,
    build_watercut_links,
    diagnose_watercut,
    haversine_km,
    injection_csv_template,
    injection_from_csv,
    metadata_csv_template,
    metadata_from_csv,
    production_csv_template,
    production_from_csv,
)
from .passport import (
    ALLOWED_ATTACHMENT_MIMES,
    MAX_ATTACHMENT_SIZE,
    PASSPORT_SCHEMA_VERSION,
    AttachmentMetadata,
    PassportConflictError,
    PassportEvent,
    PassportEventType,
    PassportNotFoundError,
    PassportRepository,
    PassportStorageError,
    new_passport_event,
    passport_summary,
    passport_timeline,
    safe_attachment_name,
)
from .smart_map import (
    DISCLAIMER as SMART_MAP_DISCLAIMER,
    MECHANISMS as SMART_MAP_MECHANISMS,
    InfrastructureAsset,
    RiskObservation,
    SmartMapConflictError,
    SmartMapNotFoundError,
    SmartMapPolicy,
    SmartMapRepository,
    SmartMapService,
    SmartMapStorageError,
    assets_from_geojson,
    observation_from_diagnosed,
    risk_csv_template,
    risk_status as smart_map_risk_status,
)
from .digital_twin import (
    ASSOCIATION_DISCLAIMER,
    MODEL_VERSION as DIGITAL_TWIN_MODEL_VERSION,
    SCHEMA_VERSION as DIGITAL_TWIN_SCHEMA_VERSION,
    ChangeExplanation,
    DigitalTwinEvent,
    DigitalTwinService,
    EquipmentAdapter,
    EventCategory,
    ManualAdapter,
    ManualEventRepository,
    MetricValue,
    PassportAdapter,
    TimelineEvent,
    TreatmentAdapter,
    TwinAmbiguousError,
    TwinConflictError,
    TwinHealthPolicy,
    TwinNotFoundError,
    TwinSnapshot,
    TwinStorageError,
    WatercutAdapter,
    WellIdentity,
    build_default_service,
    manual_csv_template,
    manual_event,
    manual_events_from_csv,
    normalize_well_name,
    stable_event_id,
)

__all__ = [
    "CANONICAL_DOSE_UNIT",
    "CHEMICAL_SCHEMA_VERSION",
    "ChemicalConflictError",
    "ChemicalNotFoundError",
    "ChemicalProduct",
    "ChemicalRecommendation",
    "ChemicalRepository",
    "ChemicalStorageError",
    "ChemicalDoseResponseEnvelope",
    "ChemicalDoseResponsePoint",
    "StockLot",
    "StockReservation",
    "StockTransaction",
    "convert_quantity",
    "deterministic_consumption_forecast",
    "dose_to_kg_m3",
    "recommend_products",
    "shortage_report",
    "COMPATIBILITY_MODEL_VERSION",
    "CompatibilityResult",
    "CompatibilityWater",
    "DepositionLocation",
    "DoseResponseCurve",
    "DoseResponsePoint",
    "InhibitorRecommendation",
    "MineralScreen",
    "ProfilePoint",
    "RatioScreen",
    "UnsafeInterval",
    "default_mix_fractions",
    "evaluate_compatibility",
    "mix_waters",
    "screen_minerals",
    "water_compatibility",
    "CorrosionIntegrityInput",
    "ForecastCalibrationEvidence",
    "ForecastCalibrationMetadata",
    "ForecastConfig",
    "ForecastEvent",
    "ForecastHistory",
    "ForecastMechanism",
    "ForecastSnapshot",
    "ForecastStatus",
    "ForecastSummary",
    "LikelihoodCategory",
    "ObservedForecastEvent",
    "TemporalEvidence",
    "WellForecast",
    "forecast_well",
    "BASELINE_CALIBRATION",
    "CorrosionConditions",
    "DataProvenance",
    "DataQuality",
    "DataQualityError",
    "DEFAULT_RISK_POLICY",
    "DEFAULT_MASTER_PLAN_POLICY",
    "DiagnosedWell",
    "FieldMapData",
    "FieldMapPoint",
    "FieldMapSummary",
    "MAP_STATUS_COLORS",
    "MAP_STATUS_LABELS",
    "map_status",
    "prepare_field_map",
    "valid_coordinates",
    "DiagnosisResult",
    "MasterPlan",
    "MasterPlanPolicy",
    "MasterPlanSummary",
    "MasterTask",
    "OilLossEstimate",
    "RISK_ECONOMICS_FORMULAS",
    "RiskEconomicsBreakdown",
    "RiskEconomicsInput",
    "RiskEconomicsResult",
    "RiskEconomicsStatus",
    "calculate_risk_economics",
    "EffectOverride",
    "ScenarioChanges",
    "ScenarioComparison",
    "ScenarioEconomics",
    "ScenarioSnapshot",
    "ScenarioStatus",
    "compare_scenario",
    "MECHANISM_WEIGHTS",
    "RiskPolicy",
    "RuntimeCalibration",
    "ScenarioInterval",
    "UncertaintyConfig",
    "UncertaintyResult",
    "FluidProperties",
    "ProductionRate",
    "ThermalParams",
    "WaterAnalysis",
    "WaxProperties",
    "WellCase",
    "WellGeometry",
    "assess_quality",
    "corrosion_rate_1995",
    "corrosion_severity",
    "diagnose",
    "generate_master_plan",
    "halite_saturation_index",
    "pressure_profile",
    "rank_wells",
    "stiff_davis_index",
    "temperature_profile",
    "wax_onset_depth",
    "DEFAULT_MIN_SAMPLE_SIZE",
    "TREATMENT_SCHEMA_VERSION",
    "TreatmentConflictError",
    "TreatmentNotFoundError",
    "TreatmentRecord",
    "TreatmentRepository",
    "TreatmentStatus",
    "TreatmentStorageError",
    "compare_reagents",
    "new_treatment",
    "treatment_analytics",
    "treatment_effect",
    "treatment_summary",
    "treatments_from_csv",
    "treatments_to_csv",
    "EQUIPMENT_DISCLAIMER",
    "EQUIPMENT_SCHEMA_VERSION",
    "EQUIPMENT_MODEL_VERSION",
    "EquipmentConflictError",
    "EquipmentForecast",
    "EquipmentMetadata",
    "EquipmentNotFoundError",
    "EquipmentRepository",
    "EquipmentRiskPolicy",
    "EquipmentStorageError",
    "LiftType",
    "RiskCause",
    "TelemetrySnapshot",
    "forecast_equipment",
    "normalize_lift",
    "telemetry_csv_template",
    "telemetry_from_csv",
    "telemetry_to_csv",
    "ALLOWED_ATTACHMENT_MIMES",
    "MAX_ATTACHMENT_SIZE",
    "PASSPORT_SCHEMA_VERSION",
    "AttachmentMetadata",
    "PassportConflictError",
    "PassportEvent",
    "PassportEventType",
    "PassportNotFoundError",
    "PassportRepository",
    "PassportStorageError",
    "new_passport_event",
    "passport_summary",
    "passport_timeline",
    "safe_attachment_name",
    "ASSOCIATION_DISCLAIMER",
    "DIGITAL_TWIN_MODEL_VERSION",
    "DIGITAL_TWIN_SCHEMA_VERSION",
    "ChangeExplanation",
    "DigitalTwinEvent",
    "DigitalTwinService",
    "EventCategory",
    "ManualEventRepository",
    "MetricValue",
    "TimelineEvent",
    "TwinAmbiguousError",
    "TwinConflictError",
    "TwinHealthPolicy",
    "TwinNotFoundError",
    "TwinSnapshot",
    "TwinStorageError",
    "WellIdentity",
    "build_default_service",
    "manual_csv_template",
    "manual_event",
    "manual_events_from_csv",
    "normalize_well_name",
    "stable_event_id",
]
